### ISSUE TITLE
Team Green is not FAIR

### ISSUE THREAD

**Issue by egonw** [elixir-europe/BioHackathon-projects-2019#44]
I got complaints that, particularly, Team Green is not FAIR. For example, we don't have identifiers for players (ORCID has been suggested) and we don't have ontologies to describe our skills. I mean, seriously, I cannot find anything on BioPortal for "I would kill for the nomination"! :(

**Comment by rwwh** [comment]
I have an issue with this issue: it looks more like an epic than a story.... 
Lets split it up:

- [ ] FAIR metrics for teams.
- [ ] We need proper identifiers for the contenders
- [ ] We need to identify a tabletennis skill ontology, or something more generic that can be made to fit

The first one we can solve each individually using our team document. 
For GDPR reasons I will not post the link here....

We really have to make sure to become the most FAIR team. FAIR play FTW!

**Comment by schymane** [comment]
I FAIRified my response ;-)
Surely we need a FAIR play prize? (a la "spirit" prize in Ultimate Frisbee?)

**Comment by DeniseSl22** [comment]
We could start building the ontology with [this](https://www.optimumtennis.net/tennis-skills-and-techniques.htm) resources; tennis is close enough to table tennis right?

**Comment by rombaum** [comment]
@DeniseSl22 can we merge this skills with table skills & techniques? I think then we will be on a good way.

**Comment by MarekSuchanek** [comment]
@DeniseSl22 @rombaum Great ideas 👍 🎾 I think that instead of merging, it should be more convenient to run some automatic ontology mapping tool to find an alignment with correspondences between tennis and table-use vocabularies. For example, semantic relations between `o1:serve` (a table) and `o2:serve` (a tennis ball) or `o1:BreakPoint` (point that could result to win) and `o2:BreakPoint` (point that is the result of the loss, since it is where your table broke).

**Comment by uniqueg** [comment]
I think the labels "Team Green" and "help wanted" are redundant.

**Comment by DeniseSl22** [comment]
Yes, I think this is a perfect example to check how we can align ontologies for different but related disciplines together @rombaum @MarekSuchanek  . And we definitely need some help with this, since I'm neither a table nor tennis nor table tennis expert @uniqueg ;) . Who got nominated to take the win on behalf of our team @rwwh ?

**Comment by rwwh** [comment]
Green will cheer for Vahid Kiani and Jacek Lebioda!

**Comment by egonw** [comment]
FAIR did not bring is much.
